# Dependencies

# Permalinks
permalink:        pretty


# Setup
title:            DSSG2020 Disinformation
tagline:          ''
description:      'A 2020 Data Science for Social Good summer fellowship project at the University of Washington' 
url:              "https://uwescience.github.io"
baseurl:          "/DSSG2020-Disinformation"


paginate:         5

# Custom vars
version:          0.0.0

github:
  repo:           https://github.com/uwescience/DSSG2020-Disinformation/
